name: sample-dockerfile
services:
  - dockerfile_path: Dockerfile
    github:
      branch: 'feature/test'
      deploy_on_push: true
      repo: WebGL3D/sample-digitalocean-app
    name: sample-dockerfile
