name: sample-dockerfile
services:
  - dockerfile_path: services/sample/Dockerfile
    source_dir: services/sample
    github:
      branch: 'feature/test'
      deploy_on_push: true
      repo: WebGL3D/sample-digitalocean-app
    name: sample-dockerfile
